mindmap
  root((DG Form))
    Pain Points (ปัญหาเดิมๆ)
      ส่งไฟล์ Excel โยนไปมา
      Format ไม่ตรงกัน
      ไม่มีที่เก็บรวบรวม
      เปลืองงบทำ Server
    Value Proposition (สิ่งที่เรามอบให้)
      UI/UX ใช้งานง่าย
      มีระบบ Bulk Import สบาย
      100% Serverless
      ฟรีค่าดูแล (Zero Cost)
    Concept Idea
      Web App แบบ Static
      ใช้ Google Sheet เป็น Database
      แยก Sheet ตามหน่วยงาน (Multi-tenant)
